name: 'RoamJS Publish'
description: 'GitHub Action for publishing extensions to RoamJS'
inputs:
  token:
    description: 'Your RoamJS Developer Token'
    required: true
  source:
    description: 'The directory to deploy from'
    required: true
  path:
    description: 'The RoamJS path to deploy to'
    required: true
  release_token:
    description: 'The Github Token with Release API permission'
    required: false
  branch:
    descripton: 'The branch to deploy to'
    required: false
  email:
    descripton: 'The email of the RoamJS user deploying. Required for latest token scheme'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'